//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unique.EcommGroceryStore.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSubCategoryMaster
    {
        public int SubSubCategoryId { get; set; }
        public int SubCategoryId { get; set; }
        public string Name { get; set; }
    
        public virtual SubCategoryMaster SubCategoryMaster { get; set; }
    }
}
